- hosts: all
  tasks:
     - package: 
          name: "httpd"
          state: present

     - copy:  
          src: "/var/www/html/index.html"
          dest: "/var/www/html/index.html"

     - service: 
          name: "httpd"
          state: restarted
          enabled: yes
#     - firewalld:
 #         state: enabled
  #        port: 80/tcp
   #       permanent: yes
    #      immediate: yes 
